import Head from 'next/head'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1>Title</h1>
				<p>
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum quasi magnam consequuntur dolorum quo facere
					beatae modi, aperiam porro similique?
				</p>
			</main>
		</div>
	)
}
